name: Build Windows and publish

on: 
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Build and publish for windows
      env:
        GITHUB_TOKEN: ${{github.token}}
      run: npm run publish -- --platform=win32

      
