name: Build Windows and configure LFS

on: 
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Build windows for verification
      run: npm run make -- --platform=win32

    - name: Setup Git LFS tracking
      shell: bash
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git lfs install
        git lfs track "dist/make/**"
        git add .gitattributes
        # Commit and push only if .gitattributes changed
        if git diff --staged --quiet; then
          echo ".gitattributes is already up-to-date."
        else
          git commit -m "ci: Configure Git LFS for build artifacts"
          git push -f origin master
        fi
